### ISSUE TITLE
Lack the MeshGeodesics.csproj

### ISSUE THREAD

**Issue by arch-tu** [AlanRynne/Geodesic-Patterns#2]
hi,

when I try to  compile  the code, it reminds me that lack the "MeshGeodesics.csproj " file.

**Comment by AlanRynne** [comment]
Hi again! I will check this out too, I did a restructuring of the protect but I’m afraid it was left half done😰.
While I try to fix you other issue (#1) I’ll also look into this!👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlanRynne** [comment]
I'm pushing some changes to the master branch that should fix this (#3)! The correct code was on the PiecewiseGeodesic branch, which I am also deleting when I finish the pull request to avoid confusion.
I'm closing this issue, since the "missing" csproj error has been solved, but feel free to reopen if you continue to have trouble!
